entities: dict[str, str] = {
    "&lt;": "<",
    "&gt;": ">",
    "&amp;": "&",
    "&quot;": '"',
    "&#39;": "'",  # Equivalent to &apos;, but more widely supported
    "&nbsp;": " ",  # Non-breaking space
    "&copy;": "©",
    "&reg;": "®",
    "&euro;": "€",
    "&pound;": "£",
    "&yen;": "¥",
    "&cent;": "¢",
    "&sect;": "§",
    "&deg;": "°",
    "&hellip;": "…",
    "&trade;": "™",
    "&laquo;": "«",
    "&raquo;": "»",
    "&ndash;": "–",
    "&mdash;": "—",
    "&iexcl;": "¡",
    "&iquest;": "¿",
    "&bull;": "•",
    "&middot;": "·",
    "&para;": "¶",
    "&dagger;": "†",
    "&Dagger;": "‡",
    "&prime;": "′",
    "&Prime;": "″",
    "&divide;": "÷",
    "&times;": "×",
    "&plusmn;": "±",
    "&micro;": "µ",
    "&sup2;": "²",
    "&sup3;": "³",
    "&frac14;": "¼",
    "&frac12;": "½",
    "&frac34;": "¾",
    "&shy;": "\N{SOFT HYPHEN}",
}
